const EachBlogData = [
{
    id:"1",
    srcBlog:"/images1/image14.jpg",
    firstparah:"Ankle Fractures In Children",
    secondparah: "Description ",
    forthparah:"Conclusion ",
    thirdparah:"Cause ",
    firstpara:"A broken ankle, also called an ankle fracture, is a common childhood injury. This fracture involves a break in one or more of the bones that make up the ankle: the tibia (shinbone), fibula (outside ankle bone), and talus (small bone in the back part of the foot). Ankle fractures in children range form very mild to complex. Basic fractures can often be successfully treated with a simple walking boot, while more complex injuries may require surgery. An orthopaedic surgeon will provide counseling about treatment options for ankle fractures in your child, as well as longer-term follow-up care to monitor the outcome of the treatment.", 
    secondpara:"Ankle fractures in children and adolescents usually occur in the tibia or fibula and typically involve the growth plates. Growth plates are areas of cartilage, located near the ends of long bones, that harden into sold bone when a child becomes full-growh. Because growth plates are the last portion of bones to harden, they are vulnerable to fractures. During adolescence when the growth plate first begins to close and harden, transitional fractures of the maturing growth plate can occur. Two common transitional fractures of the ankle are triplane fractures and Tillaux fractures ",
    thirdpara:"Pediatric ankle injuries typically occur when a child's lower leg or foot twists unexpectedly during sports or vigorous play. Sports involving lateral motion and jumping — like basketball — may put children at higher risk for ankle injuries. For example, when jumping to defend, shoot, or rebound, a child may land on an opponent's foot, causing their foot to twist or roll to the inside or outside.",
    forthpara:"Ankle fractures are a common chidhood injury. Fractures that heal well-aligned and do not develop a growth disturbance should not cause any significant long-term problems such as arthritis or chronic pain."
},
{
    id:"2",
    srcBlog:"/images1/imagebg1.jpg",
    firstparah:"Treatments for Bladder Control Problems (Urinary Incontinence)",
    secondparah: "Make lifestyle changes ",
    forthparah:"How can I cope with bladder control problems? ",
    firstpara:"Depending on the type of urinary incontinence (UI) you have, your health care professional may recommend steps you can take on your own to try to control your symptoms.", 
    secondpara:"Drink the right amount of liquid at the right time : Ask your health care professional whether you should drink less liquid during the day. However, don’t limit liquids to the point of becoming dehydrated. Your health care professional can tell you how much and when to drink, based on your health, activities, and local climate.To limit nighttime trips to the bathroom, you may want to stop drinking liquids a few hours before bedtime, but only if your health care professional suggests it. Limiting foods and drinks with caffeine, such as chocolate, tea, coffee, and carbonated beverages, may help reduce leaks. You should also limit alcoholic drinks, which can increase how much urine your body makes.The amount of urine a person should make is different for everyone, based on how much liquid you drink, how much you sweat, how much liquid you lose by breathing, and the medicines you take. ,Be physically active : Although you may not feel like being physically active when you have UI, regular physical activity is important for weight management and good overall health. Activities such as walking, swimming, biking, and dancing can improve your health. If you’re concerned about not having a bathroom nearby during physical activity, find a place with nearby restrooms, such as a shopping mall, community park, or local gym.2Pediatric ankle injuries typically occur when a child's lower leg or foot twists unexpectedly during sports or vigorous play. Sports involving lateral motion and jumping — like basketball — may put children at higher risk for ankle injuries. For example, when jumping to defend, shoot, or rebound, a child may land on an opponent's foot, causing their foot to twist or roll to the inside or outside.",
    forthpara:"Even after treatment, you may still leak urine from time to time. Certain products can help you cope with urine leaks - Absorbent, washable incontinence underwear - You can use underwear lined with special fabric that absorbs urine.Waterproof underwear - Waterproof underwear can protect your clothes from getting wet.Adult incontinence briefs - You can wear disposable incontinence briefs that act like diapers to keep your clothes dry.Pads - You can wear disposable pads in your underwear to absorb leaking urine.Large disposable pads - You can use large pads to protect chairs and beds from urine.Special skin cleaners and creams - Special skin cleaners and creams may keep the skin around the urethra from getting irritated. Creams can help block urine from your skin.Urine deodorizing tablets - Talk with your health care professional about whether taking urine deodorizing tablets by mouth can make your urine smell less strong."
},
{
    id:"3",
    srcBlog:"/images1/image18.jpg",
    firstparah:"How to Use Protein Powder for Weight Loss",
    secondparah: "Why Is Protein Powder Good for Weight Loss?",
    forthparah:"Why You Need the Proper Amount of Protein ",
    thirdparah:"Which Type of Protein Powder Is Best for Weight Loss?",
    firstpara:"Now that the new year is underway, many people make it a goal to start a new exercise regimen and consume a healthier diet to help lose weight. For the best results, you need to practice a combination of nutritious eating and working out—and drinking protein shakes with the right protein powder can help with both of these goals.There are tons of benefits to incorporating protein shakes into your diet, but you also must balance the rest of your daily meals by consuming the right foods to fuel your body and help your metabolism burn fat. The biggest concern when following a weight loss program is that you may begin burning lean muscle instead of fat. To avoid this problem, and begin your diet in the healthiest way possible, follow these tips on how to use protein powder for weight loss this year. ", 
    secondpara:"Protein powders are a great snack replacement because they are often low in calories but high in other nutrients your body requires, including protein, calcium, iron and magnesium, amongst others. When purchasing a protein powder, however, you want to carefully examine the ingredients to ensure that there are no artificial ingredients or added sugars. Some companies will mix in sugar to make the protein powder taste better, but it can greatly hurt your fitness goals.When trying to cut calories, protein is one nutrient you need to make sure you’re receiving enough of or you’ll begin to suffer from uncomfortable and unhealthy side effects like fatigue and muscle weakness. Protein helps fuel your muscles and rebuild them after a workout, so without enough protein in your diet, your exercise routine will suffer as well. Some people choose to drink protein shakes first thing in the morning as a meal replacement for breakfast. Your body requires protein in the morning because it helps to kickstart your metabolism, which will aid in burning off calories and fat for the rest of the day.",
    thirdpara:"Protein powders are available in several different forms—whey and casein being the most popular choices. However, if you follow a plant-based diet, you will want to use a different type of protein as both of these are derived from cows, making them dairy products. Try pea protein, hemp protein and soy protein.",
    forthpara:"Protein is vital to leading a healthy lifestyle. Many people who begin a new diet think that eating less, in general, will help them to drop pounds, but as mentioned, you need to be careful about which types of foods you cut from your diet. Protein should never be something you limit when trying to lose weight because nearly everything in your body is composed of protein. Without nourishing your body with this essential nutrient, you’ll begin to suffer the side effects and put yourself at risk of health concerns like decreased immune system health. Protein also helps to satiate your hunger and reduce cravings throughout the day."
},
{
    id:"4",
    srcBlog:"/images1/image9.jpg",
    firstparah:"What is a cervicogenic headache?",
    secondparah: "Symptoms",
    forthparah:"Summary",
    thirdparah:"What causes a cervicogenic headache?",
    firstpara:"Cervicogenic headaches are secondary headaches. Secondary headaches are those caused by an underlying condition, such as neck injuries, infections, or severe high blood pressure. This sets them apart from primary headaches, such as migraines and cluster headaches.The pain caused by a cervicogenic headache begins in the neck and the back of the head and radiates towards the front of the head. People may confuse cervicogenic headaches with migraines and tension headaches, both of which can cause neck pain.In this article, we discuss some symptoms, causes, and treatments for cervicogenic headaches.", 
    secondpara:"Typically, people who have cervicogenic headaches experience a headache accompanied by neck pain and stiffness. Certain neck movements can provoke cervicogenic headaches.In most cases, cervicogenic headaches develop on one side of the head, starting from the back of the head and neck and radiating toward the front.Some other symptoms of a cervicogenic headache include:a reduced range of motion in the neck,pain on one side of the face or head,pain and stiffness of the neck,pain around the eyes,pain in the neck, shoulder, or arm on one side,head pain that is triggered by certain neck movements or positions,sensitivity to light and noise,nausea,blurred vision",
    thirdpara:" Cervicogenic headaches result from structural problems in the neck and are often due to problems with vertebrae at the top of the spine, called the cervical vertebrae, and specifically the C2-3 vertebra.Some people develop cervicogenic headaches because they work in jobs that involve them straining their necks. These jobs include hair stylists, manual laborers, and drivers.People can also develop cervicogenic headaches after an injury to the neck. This is better known as whiplash.",
    forthpara:"A cervicogenic headache is a type of secondary headache that is caused by problems with the neck. Causes of a cervicogenic headache include malformations of the cervical vertebrae, injuries to the neck, inflammation, and other medical conditions.If left untreated, a cervicogenic headache can worsen and become debilitating. People can experience chronic, or recurrent, headaches that do not respond to medication.People who have chronic cervicogenic headaches can work with their healthcare provider to develop a comprehensive treatment plan that will address their symptoms.People can relieve their symptoms at home, or through a combination of therapeutic, surgical, and medicinal methods."
},
{
    id:"5",
    srcBlog:"/images1/Gastroenterology.png",
    firstparah:"What is Gastroenterology?",
    secondparah: "The symptoms of a Gastroenterology disease vary but they include:",
    firstpara:"According to the American College of Gastroenterology, Gastroenterology is the study of the normal function and diseases of the esophagus, stomach, small intestine, colon and rectum, pancreas, gallbladder, bile ducts and liver. A gastroenterologist needs to have a detailed understanding of the normal physiology of all the above mentioned organs as well as motility through the intestines and gastrointestinal tract in order to maintain a healthy digestion, absorption of nutrients,  removal of waste and metabolic processes. A gastroenterologist also needs to have a clear understanding of ailments affecting the organs of the gastrointestinal system like:esophageal cancers,gastric cancers,achalasia,colon and bowel cancers,gastroesophageal reflux,a host of other disease conditions.", 
    secondpara:"If you have constant complaints to your family doctor about digestive problems such as frequent abdominal pain, nausea, or heartburn then something is affecting your digestive system. Your doctor may recommend some lifestyle changes or treat the condition with over-the-counter or prescription drugs to prevent your symptoms from worsening. Before referring you to a gastroenterologist, your General Practitioner (GP) will likely examine you first. They may in some cases order specialised tests, such as an abdominal scan or blood tests. This is sometimes enough to pinpoint the condition and recommend a treatment. If the problem persists however, your doctor may recommend you consult a gastroenterologist.The symptoms of a Gastroenterology disease vary but they include:Abdominal pain and discomfort, Bleeding in the digestive tract,Constipation and Diarrhoea",
},
{
    id:"6",
    srcBlog:"/images1/image22.jpg",
    firstparah:"Overview",
    secondparah: "Symptoms of heart disease in your blood vessels",
    thirdparah:"Heart disease symptoms caused by heart valve problems (valvular heart disease)",
    firstpara:" Heart disease describes a range of conditions that affect your heart. Heart diseases include:Blood vessel disease, such as coronary artery disease,Heart rhythm problems (arrhythmias),Heart defects you're born with (congenital heart defects),Heart valve disease,Disease of the heart muscle,Heart infection", 
    secondpara:"A buildup of fatty plaques in your arteries, or atherosclerosis (ath-ur-o-skluh-ROE-sis) can damage your blood vessels and heart. Plaque buildup causes narrowed or blocked blood vessels that can lead to a heart attack, chest pain (angina) or stroke.Coronary artery disease symptoms may be different for men and women. For instance, men are more likely to have chest pain. Women are more likely to have other signs and symptoms along with chest discomfort, such as shortness of breath, nausea and extreme fatigue.Signs and symptoms can include:Chest pain, chest tightness, chest pressure and chest discomfort (angina),Shortness of breath,Pain, numbness, weakness or coldness in your legs or arms if the blood vessels in those parts of your body are narrowed,Pain in the neck, jaw, throat, upper abdomen or back.You might not be diagnosed with coronary artery disease until you have a heart attack, angina, stroke or heart failure. It's important to watch for cardiovascular symptoms and discuss concerns with your doctor. Cardiovascular disease can sometimes be found early with regular evaluations.",
    thirdpara:"The heart has four valves — the aortic, mitral, pulmonary and tricuspid valves — that open and close to direct blood flow through your heart. Many things can damage your heart valves, leading to narrowing (stenosis), leaking (regurgitation or insufficiency) or improper closing (prolapse).Depending on which valve isn't working properly, valvular heart disease signs and symptoms generally include:Fatigue,Shortness of breath,Irregular heartbeat,Swollen feet or ankles,Chest pain",
},
{
    id:"7",
    srcBlog:"/images1/oncology.jpg",
    firstparah:"What is Oncology?",
    secondparah: "What is cancer?",
    forthparah:"Oncology diagnostic tools",
    thirdparah:"Role of an oncologist",
    firstpara:"The term oncology literally means a branch of science that deals with tumours and cancers. The word “onco” means bulk, mass, or tumor while “-logy” means study.", 
    secondpara:"Each of the cells of the body have a tightly regulated system that controls their growth, maturity, reproduction and eventual death. Cancer begins when cells in a part of the body start to grow out of control. There are many kinds of cancer, but they all start because of out-of-control growth of abnormal cells.",
    thirdpara:"Medical professionals who practice oncology are called Cancer specialists or oncologists. These oncologists have several specific roles. They help in diagnosis of the cancer, help in staging the cancer and grading the aggressive nature of the cancer.",
    forthpara:"The most important diagnostic tool remains the clinical history of the patient. Common symptoms that point towards cancer include fatigue, weight loss, unexplained anemia, fever of unknown origin etc.Oncology depends on diagnostic tools like biopsy or removal of bits of the tumour tissue and examining it under the microscope. Other diagnostic tools include endoscopy for the gastrointestinal tract, imaging studies like X-rays, CT scanning, MRI scanning, ultrasound and other radiological techniques, Scintigraphy, Single Photon Emission Computed Tomography, Positron emission tomography and nuclear medicine techniques etc.Common methods include blood tests for biological or tumor markers. Rise of these markers in blood may be indicative of the cancer."
}

]
module.exports = EachBlogData;
